name: weather_app
description: "A simple weather app"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.2.0
  flutter_spinkit: ^5.2.0
  geolocator: ^10.1.0
  flutter_dotenv: ^5.1.0
  font_awesome_flutter: ^10.6.0

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
  - images/
  - .env

  fonts:
    - family: Spartan MB
      fonts:
        - asset: fonts/SpartanMB-Black.otf
          weight: 900

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "images/icon/weather-icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21